services:
  gv-web:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - gv
    restart: unless-stopped

networks:
  gv:
    external: true
