name: Deploy 
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Sync and ReDeploy
        run: |
          export PATH="$PATH:/home/ocp/.bun/bin"
          TARGET_DIR="/home/ocp/docker/gv/gv-web"


          cd $TARGET_DIR
          git pull
          make up
